version: '1'
services:

  gl-mongo:
    image: mongo
    restart: always
    container_name: gl-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    expose:
      - 27017
    ports:
      - '27017:27017'
    # networks:
    #   - backend

  gl-blzapp:
    build: ./Google-Like-Blazor/
    # image: GL-blzapp
    restart: always
    container_name: gl-blzapp
    depends_on:
      - gl-mongo
    environment:
        - Logging__Loglevel__Default=Debug
        - Logging__Loglevel__Microsoft.AspNetCore=Debug
        - ASPNETCORE_URLS=http://+:80
    ports: 
      - '8080:80'
      - '8081:443'
    links:
      - gl-mongo

    # networks:
    #   - backend
    #   - frontend
  
# networks:
#   backend:
#   frontend: