global using Microsoft.Extensions.Options;
global using Microsoft.AspNetCore.Components;
global using BlazorPro.Spinkit;
global using MongoDB.Driver;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using MongoDB.Driver.GridFS;
global using MudBlazor;
global using MudBlazor.Services;
global using Google_Like_Blazor.Services;
global using Google_Like_Blazor.Data;
global using Tewr.Blazor.FileReader;
global using Google_Like_Blazor.Components;
global using Google_Like_Blazor.Utils;

global using Microsoft.Extensions.Caching.Memory;
global using StackExchange.Redis;
global using UglyToad.PdfPig;
global using UglyToad.PdfPig.Content;
global using Color = MudBlazor.Color;
global using Size = MudBlazor.Size;
global using Margin = MudBlazor.Margin;
global using ButtonType = MudBlazor.ButtonType;