name: Publish Docker img

on:
  push:
    branches: [ "main" ]

#jobs:
#  push_to_registry:
#   name: push docker img to dockerhub
#   runs-on: ubuntu-latest
#   steps:
#    - name: Log in to Docker Hub
#      uses: docker/login-action@v3.0.0
#      with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_TOKEN }}
#    - name: Extract metadata (tags, labels) for Docker
#      id: meta
#      uses: docker/metadata-action@v5.0.0
#      with:
#        images: GL/gl-blzapp
#      
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v5.0.0
#      with:
#        context: ./Google-Like-Blazor/
#        file: ./Dockerfile
#        push: true
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}    
